# Generated by Django 5.2.7 on 2025-10-18 14:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(help_text='Room temperature in Celsius')),
                ('light_level', models.IntegerField(help_text='Light level in lux')),
                ('noise_level', models.IntegerField(help_text='Noise level in dB')),
                ('hue_lights_status', models.TextField(blank=True, help_text='Status of Philips Hue lights', null=True)),
                ('nest_thermostat_status', models.TextField(blank=True, help_text='Status of Nest thermostat', null=True)),
                ('smart_plugs_status', models.TextField(blank=True, help_text='Status of smart plugs', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('deep_work', 'Deep Work'), ('creative', 'Creative Work'), ('analytical', 'Analytical Work'), ('learning', 'Learning'), ('writing', 'Writing'), ('coding', 'Coding')], default='deep_work', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_temperature', models.FloatField(help_text='Room temperature at session start in Celsius')),
                ('start_light_level', models.IntegerField(help_text='Light level at session start in lux')),
                ('start_noise_level', models.IntegerField(help_text='Noise level at session start in dB')),
                ('distractions_count', models.IntegerField(default=0)),
                ('focus_score', models.IntegerField(help_text='Focus score from 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_temperature', models.FloatField(default=22.0, help_text='Preferred room temperature in Celsius')),
                ('preferred_light_level', models.IntegerField(default=300, help_text='Preferred light level in lux')),
                ('preferred_noise_level', models.IntegerField(default=40, help_text='Preferred noise level in dB')),
                ('focus_duration_preference', models.IntegerField(default=25, help_text='Preferred focus session duration in minutes')),
                ('break_duration_preference', models.IntegerField(default=5, help_text='Preferred break duration in minutes')),
                ('philips_hue_bridge_ip', models.CharField(blank=True, help_text='IP address of Philips Hue Bridge', max_length=15, null=True)),
                ('nest_token', models.CharField(blank=True, help_text='Nest API token', max_length=255, null=True)),
                ('smart_plug_ids', models.TextField(blank=True, help_text='Comma-separated list of smart plug IDs', null=True)),
                ('phone_sync_enabled', models.BooleanField(default=False, help_text='Enable phone sync for Do Not Disturb')),
                ('calendar_integration_enabled', models.BooleanField(default=False, help_text='Enable calendar integration')),
                ('browser_focus_mode_enabled', models.BooleanField(default=True, help_text='Enable browser focus mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductivityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_focus_time', models.DurationField(help_text='Total focus time for the day')),
                ('average_focus_score', models.IntegerField(help_text='Average focus score from 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('distractions_count', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('session_completion_rate', models.FloatField(help_text='Completion rate of focus sessions (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('optimal_temperature', models.FloatField(help_text='Most productive temperature in Celsius')),
                ('optimal_light_level', models.IntegerField(help_text='Most productive light level in lux')),
                ('optimal_noise_level', models.IntegerField(help_text='Most productive noise level in dB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
