# Generated by Django 5.2.12 on 2026-03-04 13:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='environmentlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='focussession',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='productivitymetric',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('team_lead', 'Team Lead')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='environmentlog',
            name='hue_lights_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='environmentlog',
            name='nest_thermostat_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='environmentlog',
            name='smart_plugs_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productivitymetric',
            name='session_completion_rate',
            field=models.FloatField(help_text='Completion rate (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='browser_focus_mode_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='calendar_integration_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nest_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='philips_hue_bridge_ip',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smart_plug_ids',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='environmentlog',
            index=models.Index(fields=['user', '-timestamp'], name='flowspace_e_user_id_c47703_idx'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', '-start_time'], name='flowspace_f_user_id_4292fe_idx'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', 'task_type'], name='flowspace_f_user_id_45b6d8_idx'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['start_time'], name='flowspace_f_start_t_380d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='productivitymetric',
            index=models.Index(fields=['user', '-date'], name='flowspace_p_user_id_f33826_idx'),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='flowspace.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='flowspace.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('user', 'team')},
        ),
    ]
