# Generated by Django 5.2.12 on 2026-03-04 13:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspace', '0002_team_teammembership_alter_environmentlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('streak', 'Streak'), ('sessions', 'Sessions'), ('focus_score', 'Focus Score'), ('time', 'Total Time'), ('environment', 'Environment'), ('team', 'Team'), ('special', 'Special')], db_index=True, max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('icon', models.CharField(default='trophy', help_text='Emoji or icon name', max_length=50)),
                ('points', models.IntegerField(default=10)),
                ('criteria_type', models.CharField(help_text='e.g. streak_days, total_sessions, avg_score', max_length=50)),
                ('criteria_value', models.IntegerField(help_text='Threshold value to unlock (e.g. 7 for "7-day streak")')),
                ('requires_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'criteria_value'],
            },
        ),
        migrations.CreateModel(
            name='DistractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('distraction_type', models.CharField(choices=[('phone', 'Phone Notification'), ('email', 'Email'), ('chat', 'Chat Message'), ('social_media', 'Social Media'), ('meeting', 'Unplanned Meeting'), ('colleague', 'Colleague Interruption'), ('noise', 'Environmental Noise'), ('internal', 'Internal (mind wandering)'), ('break', 'Unplanned Break'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('severity', models.IntegerField(choices=[(1, 'Minor - recovered in <30s'), (2, 'Moderate - recovered in 1-5min'), (3, 'Major - recovered in 5-15min'), (4, 'Severe - session significantly impacted'), (5, 'Critical - session abandoned')], default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('recovery_time_seconds', models.IntegerField(default=0, help_text='Time taken to refocus in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('max_sessions_per_day', models.IntegerField(default=5)),
                ('max_team_members', models.IntegerField(default=0)),
                ('max_environment_devices', models.IntegerField(default=2)),
                ('analytics_retention_days', models.IntegerField(default=30)),
                ('ai_recommendations_enabled', models.BooleanField(default=False)),
                ('advanced_analytics_enabled', models.BooleanField(default=False)),
                ('custom_soundscapes_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_focus_duration', models.IntegerField(default=25, help_text='Default focus duration in minutes for this workspace')),
                ('default_break_duration', models.IntegerField(default=5, help_text='Default break duration in minutes')),
                ('daily_focus_goal_minutes', models.IntegerField(default=240, help_text='Team daily focus goal in minutes')),
                ('weekly_session_goal', models.IntegerField(default=20, help_text='Team weekly session target')),
                ('share_focus_scores', models.BooleanField(default=True, help_text='Share individual focus scores with team')),
                ('share_streaks', models.BooleanField(default=True, help_text='Share streak data with team')),
                ('leaderboard_enabled', models.BooleanField(default=True, help_text='Enable team leaderboard')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('team', 'Team Only'), ('public', 'Public')], default='team', max_length=10)),
                ('daily_standup_enabled', models.BooleanField(default=False)),
                ('standup_time', models.TimeField(blank=True, null=True)),
                ('weekly_report_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak_days', models.IntegerField(db_index=True, default=0)),
                ('current_streak_start', models.DateField(blank=True, null=True)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('longest_streak_start', models.DateField(blank=True, null=True)),
                ('longest_streak_end', models.DateField(blank=True, null=True)),
                ('last_active_date', models.DateField(blank=True, db_index=True, null=True)),
                ('active_days_this_week', models.IntegerField(default=0)),
                ('active_days_this_month', models.IntegerField(default=0)),
                ('total_active_days', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='focussession',
            name='flowspace_f_start_t_380d5e_idx',
        ),
        migrations.RenameIndex(
            model_name='environmentlog',
            new_name='idx_envlog_user_time',
            old_name='flowspace_e_user_id_c47703_idx',
        ),
        migrations.RenameIndex(
            model_name='focussession',
            new_name='idx_session_user_time',
            old_name='flowspace_f_user_id_4292fe_idx',
        ),
        migrations.RenameIndex(
            model_name='focussession',
            new_name='idx_session_user_type',
            old_name='flowspace_f_user_id_45b6d8_idx',
        ),
        migrations.RenameIndex(
            model_name='productivitymetric',
            new_name='idx_metric_user_date',
            old_name='flowspace_p_user_id_f33826_idx',
        ),
        migrations.AddField(
            model_name='focussession',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Optional label like "Sprint planning" or "Chapter 3 review"', max_length=200),
        ),
        migrations.AddField(
            model_name='focussession',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='focussession',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team context for this session (if collaborative)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_sessions', to='flowspace.team'),
        ),
        migrations.AddField(
            model_name='productivitymetric',
            name='avg_recovery_time_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productivitymetric',
            name='completed_session_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productivitymetric',
            name='session_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productivitymetric',
            name='top_distraction_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='environmentlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='focus_score',
            field=models.IntegerField(db_index=True, help_text='Focus score from 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productivitymetric',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='environmentlog',
            index=models.Index(fields=['-timestamp'], name='idx_envlog_timestamp'),
        ),
        migrations.AddIndex(
            model_name='environmentlog',
            index=models.Index(fields=['user', 'temperature', 'light_level', 'noise_level'], name='idx_envlog_user_env'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', 'is_completed', '-start_time'], name='idx_session_completed'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['team', '-start_time'], name='idx_session_team_time'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', '-focus_score'], name='idx_session_user_score'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['-start_time'], name='idx_session_start_global'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['-created_at'], name='idx_session_created'),
        ),
        migrations.AddIndex(
            model_name='productivitymetric',
            index=models.Index(fields=['-date', '-average_focus_score'], name='idx_metric_date_score'),
        ),
        migrations.AddIndex(
            model_name='productivitymetric',
            index=models.Index(fields=['-created_at'], name='idx_metric_created'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['owner'], name='flowspace_t_owner_i_999024_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['slug'], name='flowspace_t_slug_bb1a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user', 'team'], name='flowspace_t_user_id_12c50e_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'role'], name='flowspace_t_team_id_307809_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='flowspace_u_user_id_688c46_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='flowspace_u_role_090d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['category', 'is_active'], name='flowspace_a_categor_3087be_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['slug'], name='flowspace_a_slug_23d82e_idx'),
        ),
        migrations.AddField(
            model_name='distractionevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distraction_events', to='flowspace.focussession'),
        ),
        migrations.AddField(
            model_name='distractionevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distraction_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamworkspace',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='flowspace.team'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unlocks', to='flowspace.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstreak',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='distractionevent',
            index=models.Index(fields=['session', '-timestamp'], name='idx_distraction_session'),
        ),
        migrations.AddIndex(
            model_name='distractionevent',
            index=models.Index(fields=['user', '-timestamp'], name='idx_distraction_user_time'),
        ),
        migrations.AddIndex(
            model_name='distractionevent',
            index=models.Index(fields=['user', 'distraction_type'], name='idx_distraction_user_type'),
        ),
        migrations.AddIndex(
            model_name='distractionevent',
            index=models.Index(fields=['-created_at'], name='idx_distraction_created'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan', 'status'], name='flowspace_s_plan_0e3629_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_end'], name='flowspace_s_current_a7a985_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_customer_id'], name='flowspace_s_stripe__902310_idx'),
        ),
        migrations.AddIndex(
            model_name='teamworkspace',
            index=models.Index(fields=['team'], name='flowspace_t_team_id_556700_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', '-unlocked_at'], name='idx_userachieve_user_time'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['achievement'], name='idx_userachieve_achievement'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='userstreak',
            index=models.Index(fields=['-current_streak_days'], name='idx_streak_current'),
        ),
        migrations.AddIndex(
            model_name='userstreak',
            index=models.Index(fields=['-longest_streak_days'], name='idx_streak_longest'),
        ),
        migrations.AddIndex(
            model_name='userstreak',
            index=models.Index(fields=['last_active_date'], name='idx_streak_last_active'),
        ),
    ]
